"""
Upstream forwarding layer.

Responsibilities:
1. Maintain a shared httpx connection pool to Open WebUI;
2. Probe which API prefix the upstream supports (/api/v1 for OpenAI-compatible
   routes, /api for legacy routes);
3. Forward requests as-is, and automatically fall back to the other prefix when
   the primary prefix returns 404 (route not found).

上游转发层。

职责：
1. 维护到 Open WebUI 的共享 httpx 连接池；
2. 探测上游支持的 API 前缀（/api/v1 为 OpenAI 兼容路由，/api 为旧版路由）；
3. 把请求按原样转发，并在主前缀返回 404（路由不存在）时自动回退到另一前缀。
"""

from __future__ import annotations

import logging
from typing import Any, Callable, Dict, List, Optional

import httpx

import lang
from config import Settings
from session_store import Session

logger = logging.getLogger("webui-proxy.upstream")

# Hop-by-hop headers that must not be passed from the upstream response to the client
# 需要逐跳处理、不能从上游响应直接透传给客户端的响应头
HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "content-length",
    "content-encoding",
    # Content-Type is set by StreamingResponse's media_type to avoid duplication
    # Content-Type 由 StreamingResponse 的 media_type 负责设置，避免重复
    "content-type",
}

# Generated by this service itself; must not be passed through from the upstream,
# otherwise Date/Server would appear twice
#
# 由本服务自己生成，不应从上游透传，否则会出现 Date/Server 重复
SELF_GENERATED_HEADERS = {"date", "server"}


class UpstreamUnavailable(RuntimeError):
    """
    Cannot reach the upstream / the upstream returned an unhandleable response.

    连不上上游 / 上游返回了无法处理的响应。
    """

    def __init__(self, message: str, status_code: int = 502):
        super().__init__(message)
        self.status_code = status_code


class UpstreamClient:
    def __init__(self, settings: Settings):
        self.settings = settings
        self._client: Optional[httpx.AsyncClient] = None
        self.prefix: Optional[str] = None

    # ------------------------------------------------------------------ #
    # Lifecycle
    # 生命周期
    # ------------------------------------------------------------------ #
    async def client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                timeout=httpx.Timeout(
                    self.settings.request_timeout,
                    connect=self.settings.connect_timeout,
                ),
                limits=httpx.Limits(max_connections=100, max_keepalive_connections=20),
                follow_redirects=True,
                verify=self.settings.upstream_verify_ssl,
                trust_env=self.settings.upstream_trust_env,
            )
        return self._client

    async def aclose(self) -> None:
        if self._client is not None and not self._client.is_closed:
            await self._client.aclose()
        self._client = None

    # ------------------------------------------------------------------ #
    # Prefix probing
    # 前缀探测
    # ------------------------------------------------------------------ #
    async def detect_prefix(self, session: Session, *, refresh: bool = False) -> str:
        """
        Determine the upstream prefix. A 404 means the route does not exist;
        401/403 means the route exists but the credentials are dead.

        确定上游前缀。返回 404 表示该路由不存在，401/403 表示路由存在但凭证失效。
        """
        if self.prefix and not refresh:
            return self.prefix
        prefix, _status = await self.probe_models(session)
        return prefix

    async def probe_models(self, session: Session) -> tuple[str, int]:
        """
        Probe for a usable prefix; return (prefix, HTTP status of the probe request).

        The probe request itself is an authenticated GET /models, so its status code
        also tells whether the credentials are valid -- the startup self-check
        (_startup_check / --check) uses this to merge "find the prefix + validate the
        credentials" into a single request instead of hitting /models twice.

        探测可用前缀，返回 (前缀, 探测请求的 HTTP 状态码)。

        探测请求本身就是一次带凭证的 GET /models，状态码因此同时能用于
        判断凭证是否有效——启动自检（_startup_check / --check）据此把
        "找前缀 + 验凭证"合并为一次请求，不再对 /models 打两次。
        """
        candidates: List[str] = self.settings.prefix_candidates()
        client = await self.client()
        last_status: Optional[int] = None
        last_text: str = ""

        for prefix in candidates:
            url = self.settings.upstream_url(prefix, "models")
            try:
                resp = await client.get(url, headers=session.to_headers())
            except httpx.RequestError as exc:
                raise UpstreamUnavailable(lang.t("unavailable_connect", url=url, exc=exc)) from exc

            if resp.status_code == 404:
                last_status, last_text = resp.status_code, resp.text[:200]
                logger.debug(lang.t("probe_404", url=url))
                await resp.aclose()
                continue

            self.prefix = prefix
            logger.info(lang.t("probe_result", prefix=prefix, status=resp.status_code))
            await resp.aclose()
            return prefix, resp.status_code

        # All candidates returned 404: fall back to the first candidate so the upper
        # layer gets a real error
        #
        # 所有候选都 404：兜底用第一个候选，让上层拿到真实错误
        self.prefix = candidates[0]
        logger.warning(
            lang.t("all_404", status=last_status, prefix=self.prefix),
        )
        if last_text:
            logger.debug(lang.t("resp_fragment", text=last_text))
        return self.prefix, last_status if last_status is not None else 404

    # ------------------------------------------------------------------ #
    # Requests
    # 请求
    # ------------------------------------------------------------------ #
    async def get_models(self, session: Session) -> httpx.Response:
        prefix = await self.detect_prefix(session)
        url = self.settings.upstream_url(prefix, "models")
        client = await self.client()
        try:
            return await client.get(url, headers=session.to_headers())
        except httpx.RequestError as exc:
            raise UpstreamUnavailable(lang.t("unavailable_connect", url=url, exc=exc)) from exc

    async def _send_with_prefix_fallback(
        self,
        session: Session,
        subpath: str,
        build_request: Callable[[httpx.AsyncClient, str], httpx.Request],
        *,
        stream: bool = False,
    ) -> httpx.Response:
        """
        Send with candidate prefixes in order; if the primary prefix returns 404
        (no such route), fall back to the other candidate prefixes.

        build_request(client, url) is responsible for building the httpx.Request, so
        the caller decides the shape of body / headers; post() and forward() share
        the same fallback strategy.

        按候选前缀依次发送；主前缀返回 404（无此路由）则回退其它候选前缀。

        build_request(client, url) 负责构造 httpx.Request，由调用方决定
        body / headers 的形态，post() 与 forward() 共用同一套回退策略。
        """
        prefix = await self.detect_prefix(session)
        candidates = [prefix] + [p for p in self.settings.prefix_candidates() if p != prefix]
        client = await self.client()

        last_exc: Optional[Exception] = None
        for index, candidate in enumerate(candidates):
            url = self.settings.upstream_url(candidate, subpath)
            try:
                resp = await client.send(build_request(client, url), stream=stream)
            except httpx.RequestError as exc:
                last_exc = exc
                if index == len(candidates) - 1:
                    break
                logger.warning(lang.t("request_failed", url=url, exc=exc))
                continue

            if resp.status_code == 404 and index < len(candidates) - 1:
                logger.debug(lang.t("fallback_404", url=url, next=candidates[index + 1]))
                await resp.aclose()
                continue
            return resp

        raise UpstreamUnavailable(lang.t("unavailable_base", base=self.settings.open_webui_base_url, exc=last_exc))

    async def post(
        self,
        subpath: str,
        session: Session,
        payload: Dict[str, Any],
        *,
        stream: bool = False,
    ) -> httpx.Response:
        """
        POST JSON to the upstream; if the primary prefix returns 404 (no such
        route), fall back to the other candidate prefixes.

        POST JSON 到上游；若主前缀返回 404（无此路由）则回退到其它候选前缀。
        """

        def build(client: httpx.AsyncClient, url: str) -> httpx.Request:
            # httpx's post() has no stream parameter; must use build_request + send
            # httpx 的 post() 不支持 stream 参数，必须用 build_request + send
            return client.build_request("POST", url, headers=session.to_headers(), json=payload)

        return await self._send_with_prefix_fallback(session, subpath, build, stream=stream)

    async def forward(
        self,
        method: str,
        subpath: str,
        session: Session,
        *,
        headers: Optional[Dict[str, str]] = None,
        content: Optional[bytes] = None,
        stream: bool = False,
    ) -> httpx.Response:
        """
        Pass through a request of any method/path; fall back to other candidates
        when the primary prefix returns 404 (consistent with post()).

        Used by the /v1/* catch-all passthrough: builds no JSON body and forwards the
        caller-provided bytes and headers as-is.

        透传任意方法/路径的请求；主前缀 404 时回退其它候选（与 post 行为一致）。

        供 /v1/* 兜底透传使用：不构造 JSON 体，原样转发调用方给定的字节与请求头。
        """

        def build(client: httpx.AsyncClient, url: str) -> httpx.Request:
            return client.build_request(method, url, headers=headers, content=content)

        return await self._send_with_prefix_fallback(session, subpath, build, stream=stream)

    # ------------------------------------------------------------------ #
    # Utilities
    # 工具
    # ------------------------------------------------------------------ #
    @staticmethod
    def forward_headers(resp: httpx.Response, extra: Optional[Dict[str, str]] = None) -> Dict[str, str]:
        """
        Assemble the response headers to pass through to the client.

        Keys are lowercased so that a same-named header from extra with different
        casing is not sent twice (HTTP headers are case-insensitive; duplicates get
        joined by the client into "no, no").

        整理要透传给客户端的响应头。

        键名统一小写，避免与 extra 里大小写不同的同名头被各发一次
        （HTTP 头不区分大小写，重复下发会被客户端拼成 "no, no"）。
        """
        drop = HOP_BY_HOP_HEADERS | SELF_GENERATED_HEADERS
        headers = {
            k.lower(): v
            for k, v in resp.headers.items()
            if k.lower() not in drop
        }
        for key, value in (extra or {}).items():
            headers[key.lower()] = value
        return headers
