"""
Upstream forwarding layer.

Responsibilities:
1. Maintain a shared httpx connection pool to Open WebUI;
2. Probe which API prefix the upstream supports (/api/v1 for OpenAI-compatible
   routes, /api for legacy routes);
3. Forward requests as-is, and automatically fall back to the other prefix when
   the primary prefix returns 404 (route not found).

上游转发层。

职责：
1. 维护到 Open WebUI 的共享 httpx 连接池；
2. 探测上游支持的 API 前缀（/api/v1 为 OpenAI 兼容路由，/api 为旧版路由）；
3. 把请求按原样转发，并在主前缀返回 404（路由不存在）时自动回退到另一前缀。
"""

from __future__ import annotations

import logging
from typing import Any, Callable, Dict, List, Optional

import httpx

import lang
from config import Settings
from session_store import Session, looks_like_model_list

logger = logging.getLogger("webui-proxy.upstream")

# Upstream statuses meaning "this route exists; the credentials are the problem"
# 表示"该路由存在，问题出在凭证"的上游状态码
AUTH_FAILURE_CODES = (401, 403)

# The instance-metadata fetch (/api/config) is a bonus, never a requirement: it must not
# be able to hold /v1/models hostage for REQUEST_TIMEOUT seconds when the upstream
# half-dies (TCP established, no answer). `_ensure_instance_meta` keeps the previous
# snapshot on failure, so a short timeout is enough.
#
# 实例元信息请求（/api/config）只是附加项，绝不是必需项：上游半死（TCP 已建立但不回包）时
# 它不能把 /v1/models 拖住 REQUEST_TIMEOUT 秒。失败时 `_ensure_instance_meta` 会沿用上一份
# 快照，因此短超时足够。
INSTANCE_META_TIMEOUT = 5.0

# Hop-by-hop headers that must not be passed from the upstream response to the client
# 需要逐跳处理、不能从上游响应直接透传给客户端的响应头
HOP_BY_HOP_HEADERS = {
    "connection",
    "keep-alive",
    "proxy-authenticate",
    "proxy-authorization",
    "te",
    "trailer",
    "transfer-encoding",
    "upgrade",
    "content-length",
    # The body is forwarded in its decoded form (httpx decodes gzip/deflate/br/zstd on
    # the way out), so the upstream's Content-Encoding must not be passed on.
    #
    # 响应体是按"已解码"的形式转发的（httpx 会解码 gzip/deflate/br/zstd），
    # 因此上游的 Content-Encoding 不能透传。
    "content-encoding",
    # Content-Type is set by StreamingResponse's media_type to avoid duplication
    # Content-Type 由 StreamingResponse 的 media_type 负责设置，避免重复
    "content-type",
}

# Generated by this service itself; must not be passed through from the upstream,
# otherwise Date/Server would appear twice
#
# 由本服务自己生成，不应从上游透传，否则会出现 Date/Server 重复
SELF_GENERATED_HEADERS = {"date", "server"}


class UpstreamUnavailable(RuntimeError):
    """
    Cannot reach the upstream / the upstream returned an unhandleable response.

    连不上上游 / 上游返回了无法处理的响应。
    """

    def __init__(self, message: str, status_code: int = 502):
        super().__init__(message)
        self.status_code = status_code


class UpstreamClient:
    def __init__(self, settings: Settings):
        self.settings = settings
        self._client: Optional[httpx.AsyncClient] = None
        self.prefix: Optional[str] = None

    # ------------------------------------------------------------------ #
    # Lifecycle
    # 生命周期
    # ------------------------------------------------------------------ #
    async def client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                timeout=httpx.Timeout(
                    self.settings.request_timeout,
                    connect=self.settings.connect_timeout,
                ),
                limits=httpx.Limits(max_connections=100, max_keepalive_connections=20),
                follow_redirects=True,
                verify=self.settings.upstream_verify_ssl,
                trust_env=self.settings.upstream_trust_env,
            )
        return self._client

    async def aclose(self) -> None:
        if self._client is not None and not self._client.is_closed:
            await self._client.aclose()
        self._client = None

    # ------------------------------------------------------------------ #
    # Prefix probing
    # 前缀探测
    # ------------------------------------------------------------------ #
    async def detect_prefix(self, session: Session, *, refresh: bool = False) -> str:
        """
        Determine the upstream prefix. A 404 means the route does not exist;
        401/403 means the route exists but the credentials are dead.

        确定上游前缀。返回 404 表示该路由不存在，401/403 表示路由存在但凭证失效。
        """
        if self.prefix and not refresh:
            return self.prefix
        prefix, _status = await self.probe_prefix(session)
        return prefix

    async def probe_prefix(self, session: Session) -> tuple[str, int]:
        """
        Probe for a usable prefix; return (prefix, HTTP status of the probe request).

        A candidate only counts as the upstream prefix when its answer is conclusive:

        * 2xx whose body really is a model list -- the route exists and the credentials
          work;
        * 401/403 -- the route exists and the credentials are dead.

        Everything else says nothing about either question, so the next candidate is
        tried instead: 404 (no such route), 5xx (the upstream is unwell), and the SPA's
        HTTP 200 + HTML page for an unknown path. The returned status is therefore
        meaningful to the startup self-check (_startup_check / --check), which merges
        "find the prefix + validate the credentials" into this single request.

        探测可用前缀，返回 (前缀, 探测请求的 HTTP 状态码)。

        只有结论性的回答才算数：

        * 2xx 且响应体确实是模型列表——路由存在且凭证有效；
        * 401/403——路由存在但凭证失效。

        其它回答对这两个问题都不说明什么，因此换下一个候选前缀再试：404（无此路由）、
        5xx（上游不健康）、以及 SPA 对未知路径回的 HTTP 200 + HTML 页面。返回的状态码因此
        对启动自检（_startup_check / --check）有意义：它把"找前缀 + 验凭证"合并为这一次请求。
        """
        candidates: List[str] = self.settings.prefix_candidates()
        client = await self.client()
        last_status: Optional[int] = None
        last_text: str = ""

        for prefix in candidates:
            url = self.settings.upstream_url(prefix, "models")
            try:
                resp = await client.get(url, headers=session.to_headers())
            except httpx.RequestError as exc:
                raise UpstreamUnavailable(lang.t("unavailable_connect", url=url, exc=exc)) from exc

            status = resp.status_code
            if status in AUTH_FAILURE_CODES or (
                200 <= status < 300 and looks_like_model_list(resp)
            ):
                self.prefix = prefix
                logger.info(lang.t("probe_result", prefix=prefix, status=status))
                await resp.aclose()
                return prefix, status

            last_status, last_text = status, resp.text[:200]
            if status == 404:
                logger.debug(lang.t("probe_404", url=url))
            elif 200 <= status < 300:
                # HTTP 200 + HTML: Open WebUI's SPA answers unknown paths with a page,
                # which is not an API route at all -- a 5xx-free status is not proof.
                #
                # HTTP 200 + HTML：Open WebUI 的 SPA 会用一页 HTML 回答未知路径，
                # 那根本不是 API 路由——状态码不带 5xx 并不构成证据。
                logger.debug(lang.t("probe_not_models", url=url))
            else:
                logger.warning(lang.t("probe_unexpected", url=url, status=status))
            await resp.aclose()

        # No candidate could be confirmed: fall back to the first candidate so the upper
        # layer gets a real error
        #
        # 没有候选能被确认：兜底用第一个候选，让上层拿到真实错误
        self.prefix = candidates[0]
        logger.warning(
            lang.t("all_404", status=last_status, prefix=self.prefix),
        )
        if last_text:
            logger.debug(lang.t("resp_fragment", text=last_text))
        return self.prefix, last_status if last_status is not None else 404

    # ------------------------------------------------------------------ #
    # Requests
    # 请求
    # ------------------------------------------------------------------ #
    async def get_models(self, session: Session) -> httpx.Response:
        prefix = await self.detect_prefix(session)
        url = self.settings.upstream_url(prefix, "models")
        client = await self.client()
        try:
            return await client.get(url, headers=session.to_headers())
        except httpx.RequestError as exc:
            raise UpstreamUnavailable(lang.t("unavailable_connect", url=url, exc=exc)) from exc

    async def get_instance_config(self, session: Session) -> Optional[Dict[str, Any]]:
        """
        GET the Open WebUI instance config (`/api/config`).

        That route exists under the legacy prefix only: `/api/v1/config` is not a
        route, and Open WebUI's SPA answers unknown paths with HTTP 200 and an HTML
        page, so the usual 404-based prefix fallback cannot be used here.

        Returns None on any failure -- this metadata is a bonus, never a requirement.

        GET Open WebUI 实例配置（`/api/config`）。

        该路由只存在于旧版前缀下：`/api/v1/config` 不是路由，而 Open WebUI 的 SPA
        会用 HTTP 200 + 一页 HTML 回答未知路径，因此这里不能用基于 404 的前缀回退。

        任何失败都返回 None——这份元信息是附加项，绝不是必需项。
        """
        url = self.settings.upstream_url("/api", "config")
        client = await self.client()
        try:
            response = await client.get(
                url, headers=session.to_headers(), timeout=INSTANCE_META_TIMEOUT
            )
        except httpx.RequestError as exc:
            logger.debug(lang.t("instance_meta_failed", exc=exc))
            return None
        try:
            if response.status_code != 200:
                logger.debug(
                    lang.t("instance_meta_failed", exc=f"HTTP {response.status_code}")
                )
                return None
            try:
                payload = response.json()
            except ValueError:
                logger.debug(lang.t("instance_meta_failed", exc="response is not JSON"))
                return None
            return payload if isinstance(payload, dict) else None
        finally:
            if not response.is_closed:
                await response.aclose()

    async def _send_with_prefix_fallback(
        self,
        session: Session,
        subpath: str,
        build_request: Callable[[httpx.AsyncClient, str], httpx.Request],
        *,
        stream: bool = False,
    ) -> httpx.Response:
        """
        Send with candidate prefixes in order; if the primary prefix returns 404
        (no such route), fall back to the other candidate prefixes.

        build_request(client, url) is responsible for building the httpx.Request, so
        the caller decides the shape of body / headers; post() and forward() share
        the same fallback strategy.

        按候选前缀依次发送；主前缀返回 404（无此路由）则回退其它候选前缀。

        build_request(client, url) 负责构造 httpx.Request，由调用方决定
        body / headers 的形态，post() 与 forward() 共用同一套回退策略。
        """
        prefix = await self.detect_prefix(session)
        candidates = [prefix] + [
            candidate
            for candidate in self.settings.prefix_candidates()
            if candidate != prefix
        ]
        client = await self.client()

        last_exc: Optional[Exception] = None
        for index, candidate in enumerate(candidates):
            url = self.settings.upstream_url(candidate, subpath)
            try:
                resp = await client.send(build_request(client, url), stream=stream)
            except httpx.RequestError as exc:
                last_exc = exc
                if index == len(candidates) - 1:
                    break
                logger.warning(lang.t("request_failed", url=url, exc=exc))
                continue

            if resp.status_code == 404 and index < len(candidates) - 1:
                logger.debug(lang.t("fallback_404", url=url, next=candidates[index + 1]))
                await resp.aclose()
                continue
            return resp

        raise UpstreamUnavailable(lang.t("unavailable_base", base=self.settings.open_webui_base_url, exc=last_exc))

    async def post(
        self,
        session: Session,
        subpath: str,
        payload: Dict[str, Any],
        *,
        stream: bool = False,
    ) -> httpx.Response:
        """
        POST JSON to the upstream; if the primary prefix returns 404 (no such
        route), fall back to the other candidate prefixes.

        POST JSON 到上游；若主前缀返回 404（无此路由）则回退到其它候选前缀。
        """

        def build_request(client: httpx.AsyncClient, url: str) -> httpx.Request:
            # httpx's post() has no stream parameter; must use build_request + send
            # httpx 的 post() 不支持 stream 参数，必须用 build_request + send
            return client.build_request(
                "POST", url, headers=session.to_headers(), json=payload
            )

        return await self._send_with_prefix_fallback(session, subpath, build_request, stream=stream)

    async def forward(
        self,
        session: Session,
        method: str,
        subpath: str,
        *,
        headers: Optional[Dict[str, str]] = None,
        content: Optional[bytes] = None,
        stream: bool = False,
    ) -> httpx.Response:
        """
        Pass through a request of any method/path; fall back to other candidates
        when the primary prefix returns 404 (consistent with post()).

        Used by the /v1/* catch-all passthrough: builds no JSON body and forwards the
        caller-provided bytes and headers as-is.

        透传任意方法/路径的请求；主前缀 404 时回退其它候选（与 post 行为一致）。

        供 /v1/* 兜底透传使用：不构造 JSON 体，原样转发调用方给定的字节与请求头。
        """

        def build_request(client: httpx.AsyncClient, url: str) -> httpx.Request:
            return client.build_request(method, url, headers=headers, content=content)

        return await self._send_with_prefix_fallback(session, subpath, build_request, stream=stream)

    # ------------------------------------------------------------------ #
    # Utilities
    # 工具
    # ------------------------------------------------------------------ #
    @staticmethod
    def forward_headers(resp: httpx.Response, extra: Optional[Dict[str, str]] = None) -> Dict[str, str]:
        """
        Assemble the response headers to pass through to the client.

        Keys are lowercased so that a same-named header from extra with different
        casing is not sent twice (HTTP headers are case-insensitive; duplicates get
        joined by the client into "no, no").

        整理要透传给客户端的响应头。

        键名统一小写，避免与 extra 里大小写不同的同名头被各发一次
        （HTTP 头不区分大小写，重复下发会被客户端拼成 "no, no"）。
        """
        drop = HOP_BY_HOP_HEADERS | SELF_GENERATED_HEADERS
        headers = {
            name.lower(): value
            for name, value in resp.headers.items()
            if name.lower() not in drop
        }
        for key, value in (extra or {}).items():
            headers[key.lower()] = value
        return headers
